name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

  jobs:
    test:
      runs-on: ubuntu-latest
      services:
        mongodb:
          image: mongo
          ports: 
          - 27017:27017
      
      steps:
        - name: Git Checkout
          uses: actions/checkout@v3
        - name: npm install
          working-directory: ./backend
          run: npm install
        - name: Run Tests
          working-directory: ./backend
          run: npm test


  